create sign-in component
SpaceyaTech/Team-Berlin pull request #45
Opened 2022-11-15 19:20 UTC by NikolaGundzikova

# Description

Sign in component created.

Fixes #36 

## New component with tsx and css

No tests - no functions.

# Checklist:

- [ ✓ ] My code follows the style guidelines of this project
- [ ✓ ] I have performed a self-review of my own code
- [ ✓ ] My changes generate no new warnings
- [ ✓ ] Any dependent changes have been merged and published in downstream modules

2022-11-16 10:58 UTC, nyandika reviewed
Include the entire .idea folder in gitignore

2022-11-16 11:41 UTC, NikolaGundzikova commented
> Include the entire .idea folder in gitignore

thank you, solved

2022-11-17 08:50 UTC, nyandika approved these changes
Looks good

2022-11-17 08:50 UTC, nyandika commented on src/components/sign-in-component.tsx
> +                                           placeholder="Username Or Email adress"/>
nit: typo

2022-11-18 13:09 UTC, daveclinton requested changes

2022-11-18 13:09 UTC, daveclinton commented on src/components/sign-in-component.tsx
> +import React from "react";
Use this instead `import * as React from 'react';`

2022-11-18 13:09 UTC, daveclinton commented on src/components/sign-in-component.css
> +.OR {
Add descrptive className here

2022-11-18 13:09 UTC, daveclinton commented on src/components/sign-in-component.css
> +.loginFacebook {
All the icons can use the same styling to reduce lines of code

2022-11-18 13:13 UTC, daveclinton requested changes
Use branch naming convention from contribution guidelines of this repository

2022-11-18 13:17 UTC, daveclinton requested changes
Use camelCase for naming files. i.e signInComponent

2022-11-18 13:18 UTC, daveclinton requested changes
Use camelCase for naming files. i.e signInComponent.
And why do you have components inside if the assets folder?

2022-11-28 20:43 UTC, NikolaGundzikova commented
Hi, I updated PR.

2022-11-30 07:46 UTC, daveclinton commented
> Hi, I updated PR.

Hey @NikolaGundzikova Thats good. You can do a `git pull origin --rebase pre-dev` to fix the conflicts you have

2022-12-01 04:56 UTC, jumalaw98 requested changes
Check out the conflict and try, resolving,

2022-12-09 18:06 UTC, NikolaGundzikova commented
I resolved conflicts.

2022-12-10 12:36 UTC, jumalaw98 commented
@NikolaGundzikova  check out on this, still have some minor conflicts to tackle
![image](https://user-images.githubusercontent.com/41073697/206855403-f4d34903-0f8d-4cc8-ba6e-0f2f6ff3a9d9.png)

2022-12-12 09:44 UTC, NikolaGundzikova commented
> @NikolaGundzikova check out on this, still have some minor conflicts to tackle ![image](https://user-images.githubusercontent.com/41073697/206855403-f4d34903-0f8d-4cc8-ba6e-0f2f6ff3a9d9.png)

I don´t know why is merging blocked because I updated my branch. Everything looks good.

2022-12-12 14:14 UTC, jumalaw98 approved these changes

2022-12-12 17:49 UTC, NikolaGundzikova commented
> > Hi, I updated PR.
> 
> Hey @NikolaGundzikova Thats good. You can do a `git pull origin --rebase pre-dev` to fix the conflicts you have

Can you check my change, please?

2022-12-14 07:30 UTC, merged